version: "3"

services:
  dev:
    container_name: client_front_dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: npm run start:dev
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
  prod:
    container_name: client_front_prod
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: npm run start
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
