export const offersMock = [
  {
    id: 0,
    title: 'Senior React Native Developer',
    description: `Our mission at Netguru is to help entrepreneurs and innovators shape the world through beautiful software. We care about trust, taking ownership, and transparency. As a Certified B Corporation®, we offer a safe, inclusive and productive environment for all team members, and we’re always open to feedback. If you want to work from home and be a full time employee, great! We want to create the right opportunities for you.\n\n\nOur 10+ React Native Team is a great one and we are thrilled that we’re growing 🚀! To tell you a bit more, we are a part of Netguru's Mobile Team, consisting of 50+ developers. We deliver well-designed and optimised custom mobile app development solutions for both iOS and Android mobile platforms, in turn increasing the productivity of the business enterprise.\n\nWe are currently looking for experienced Senior React Native Developers to make our team even stronger 💪🏼. Is it you? 😊 Check it out!\n\n\nJoining Netguru's Mobile Team as a Senior React Native Developer means:\n\nworking in an experienced and knowledgeable team, in an Agile environment,\ndev-friendly processes like Continuous Integration and Code Review,\nconstant development of your hard and soft skills (e.g. at internal Webinars, external conferences, meetups, etc.),\ngrowing yourself and people around you - you will give and receive regular feedback in a team of open-minded people that will always have your back,\nambitious and verified projects- our clients come from all over the world and from different industries,\na clear and fast-paced career path based on clearly defined goals - you will frequently meet with your leader who will help you make full use of your potential,\nenjoying flextime and flexplace: adjust your daily schedule to your individual needs, work from the office or from home,\nworking on the best equipment – we will provide you with a Macbook and additional accessories for your computer to make your work even more efficient and comfortable,\nHaving a smooth start: your leader and mentor will support you along the way :)\n\n👣 Let us guide you through what you can expect while being part of our team:\n\nwe develop the Research and Development department, so each team member can contribute and develop their skills in various directions,\na typical work day usually starts with a daily project meeting, where we talk about our progress on tasks and possible blockers,\napart from coding, you will have some additional calls during the day, e.g. Project Grooming or a retrospective,\nyou will have regular O3 and F2F meetings with your leader. The O3s are all about current matters related to your projects / work in the company. F2Fs focus on your development and goals for the following quarters,\nwe love to share knowledge and we do it regularly- every two weeks we get together to present and discuss topics related to (but not only! ) React Native,\nwhen there is a break between projects, we implement our internal projects that are carried out under RnD. Be sure to check our open source - https://github.com/netguru/sticky-parallax-header ! ,\nour team is in constant contact and we always try to solve problems together. 🤗\n\nReady to apply? First check if you:\n\nHave proven 2+ years' commercial experience in developing commercial JS/mobile applications, including 1 year in RN development.\nAre familiar with state/data management libraries (e.g. redux).\nHave deep knowledge of the latest JS/TS standards and architectures.\nHave knowledge of testing standards and frameworks.\nHave the ability to work with iOS and Android distribution platforms.\nAre familiar with iOS and Android capabilities and the platforms’ basic features, such as location services, push notifications, etc.\nHave experience with Continuous Integration tools like Bitrise.\nHave experience with 3rd party services and native libraries’ integration.\nHave consulting mindset and you are ready to help Project Managers lead their projects from the technical side.\nAre a technological authority for clients and other team members, and you’re eager to help them make informed decisions.\nHave strong communication skills and good command of written and spoken English (CEFR B2+); Polish is not required.\n\n💚 We have some great Perks & Benefits for you!\n\nAccess to the WorkSmile platform offering benefits adapted to your preferences:\nMultisport card,\nPrivate health insurance package,\nLife insurance,\nAnd hundreds of other options to choose from 15 categories (shopping, leisure, travel, food, etc.)\nSupport for your growth - budget for team development,\nDiscounts on Apple products,\nOne-time 1000 PLN home office bonus,\nHome office equipment sharing option,\nVarious internal initiatives: webinars, knowledge sharing sessions, internal conferences.\n\nWhat will happen next? ➡️\n\nWe want to check your code :) You will receive a task to solve within a certain deadline,\nIf your task is solved well, you will be invited for a meeting with the recruiter- a HR Interview,\nNext step is a pair programming session with one of our developers,\nIf everything goes well, you will meet your future leader at the final online interview! :)\n\nIf you need any disability-related adaptation at any step of the recruitment process – simply let the recruiter know! We'd be happy to help.\n\n\nNot interested in long-term cooperation? Join the Netguru Talent Marketplace and have access to various project-based opportunities. Get a gig and collaborate with different companies and industries. Have a possibility to not only gain more experience but also develop a variety of skills you didn't even know you had. Work the way you like, on your terms, with no strings attached..`,
    salary_from: 16000,
    salary_to: 24600,
    paid_till: '2021-04-24T16:32:46.000Z',
    active: true,
    profession_id: 1,
    specialization_id: 1,
    company_id: 2,
    created_at: '2021-04-24T14:33:00.681Z',
    updated_at: '2021-04-24T14:33:00.681Z',
    company: {
      id: 2,
      name: 'Netguru',
      description:
        'Netguru is a consultancy, product design, and software development company founded in 2008. Netguru has become one of the fastest growing companies in EU, recognised by the Financial Times, Deloitte, and Forbes.',
      logo_file_path:
        'https://i1.sndcdn.com/avatars-000304701557-tx3yab-t500x500.jpg',
      website_url: null,
      created_at: '2021-04-24T14:32:23.185Z',
      updated_at: '2021-04-24T14:32:23.185Z',
      locations: [
        {
          id: 6,
          name: null,
          coordinates: { x: 52.4064, y: 16.9252 },
          city: 'Warszawa',
          postcode: '42-999',
          street: 'Marszałkowska 7',
          building_number: 2,
          room_number: null,
          created_at: '2021-04-26T18:06:11.901Z',
          updated_at: '2021-04-26T18:06:11.901Z',
        },
        {
          id: 7,
          name: null,
          coordinates: { x: 52.4547, y: 16.954 },
          city: 'Poznań',
          postcode: '61-612',
          street: 'Rubież 46',
          building_number: 2,
          room_number: null,
          created_at: '2021-04-26T18:06:11.901Z',
          updated_at: '2021-04-26T18:06:11.901Z',
        },
      ],
    },
  },
  {
    id: 1,
    title: 'Java developer',
    description: 'oferta desc',
    salary_from: 2500,
    salary_to: 5000,
    paid_till: '2021-04-24T16:32:46.000Z',
    active: true,
    profession_id: 1,
    specialization_id: 1,
    company_id: 2,
    created_at: '2021-04-24T14:33:00.681Z',
    updated_at: '2021-04-24T14:33:00.681Z',
    company: {
      id: 2,
      name: 'Blue energy sp. z o.o.',
      description: 'company desc',
      logo_file_path:
        'https://vfan-phinf.pstatic.net/a/327b9f/8_77gUd018svc1wpehq76b47ex_q2xwtk.jpg?type=w1000',
      website_url: null,
      created_at: '2021-04-24T14:32:23.185Z',
      updated_at: '2021-04-24T14:32:23.185Z',
      locations: [
        {
          id: 6,
          name: null,
          coordinates: { x: 52.40801894474845, y: 16.919264864185212 },
          city: 'Warszawa',
          postcode: '1',
          street: 'street2',
          building_number: 2,
          room_number: null,
          created_at: '2021-04-26T18:06:11.901Z',
          updated_at: '2021-04-26T18:06:11.901Z',
        },
      ],
    },
  },
  {
    id: 2,
    title: 'Mid JavaScript Developer',
    description: 'oferta desc',
    salary_from: 8000,
    salary_to: 14000,
    paid_till: '2021-04-24T16:32:46.000Z',
    active: true,
    profession_id: 1,
    specialization_id: 1,
    company_id: 2,
    created_at: '2021-04-24T14:33:00.681Z',
    updated_at: '2021-04-24T14:33:00.681Z',
    company: {
      id: 2,
      name: 'Digital Colliers',
      description: 'company desc',
      logo_file_path:
        'https://hips.hearstapps.com/sev.h-cdn.co/assets/15/32/1438959415-shrek-fierce.jpg',
      website_url: null,
      created_at: '2021-04-24T14:32:23.185Z',
      updated_at: '2021-04-24T14:32:23.185Z',
      locations: [
        {
          id: 6,
          name: null,
          coordinates: { x: 52.4025483576108, y: 16.96037025857706 },
          city: 'Warszawa',
          postcode: '1',
          street: 'street2',
          building_number: 2,
          room_number: null,
          created_at: '2021-04-26T18:06:11.901Z',
          updated_at: '2021-04-26T18:06:11.901Z',
        },
      ],
    },
  },
  {
    id: 3,
    title: 'Elixir Developer',
    description: 'oferta desc',
    salary_from: 7000,
    salary_to: 13000,
    paid_till: '2021-04-24T16:32:46.000Z',
    active: true,
    profession_id: 1,
    specialization_id: 1,
    company_id: 2,
    created_at: '2021-04-24T14:33:00.681Z',
    updated_at: '2021-04-24T14:33:00.681Z',
    company: {
      id: 2,
      name: 'AppUnite',
      description: 'company desc',
      logo_file_path:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJ7H2m3w_bA6VLW7UnsfyBJl-fHOOueuvKc-TmDdVHyCpHL81Ch_Q6z3tjDEwYj-Gmnu4&usqp=CAU',
      website_url: null,
      created_at: '2021-04-24T14:32:23.185Z',
      updated_at: '2021-04-24T14:32:23.185Z',
      locations: [
        {
          id: 6,
          name: null,
          coordinates: { x: 52.40446772528, y: 16.87884543876132 },
          city: 'Warszawa',
          postcode: '1',
          street: 'street2',
          building_number: 2,
          room_number: null,
          created_at: '2021-04-26T18:06:11.901Z',
          updated_at: '2021-04-26T18:06:11.901Z',
        },
      ],
    },
  },
  {
    id: 4,
    title: 'Regular Android Developer',
    description: 'oferta desc',
    salary_from: 7000,
    salary_to: 12000,
    paid_till: '2021-04-24T16:32:46.000Z',
    active: true,
    profession_id: 1,
    specialization_id: 1,
    company_id: 2,
    created_at: '2021-04-24T14:33:00.681Z',
    updated_at: '2021-04-24T14:33:00.681Z',
    company: {
      id: 2,
      name: 'comapny name',
      description: 'company desc',
      logo_file_path:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVPs7FFrJoTfAcS9V3QDJ5r7k11sXjviVEZdRteLx7hluBZRUdx0axBrUwbyDI1KL73aQ&usqp=CAU',
      website_url: null,
      created_at: '2021-04-24T14:32:23.185Z',
      updated_at: '2021-04-24T14:32:23.185Z',
      locations: [
        {
          id: 6,
          name: null,
          coordinates: { x: 52.43853035986179, y: 16.938787445366398 },
          city: 'Warszawa',
          postcode: '1',
          street: 'street2',
          building_number: 2,
          room_number: null,
          created_at: '2021-04-26T18:06:11.901Z',
          updated_at: '2021-04-26T18:06:11.901Z',
        },
      ],
    },
  },
  {
    id: 5,
    title: 'Senior Quality Assurance Engineer',
    description: 'oferta desc',
    salary_from: 14200,
    salary_to: 21200,
    paid_till: '2021-04-24T16:32:46.000Z',
    active: true,
    profession_id: 1,
    specialization_id: 1,
    company_id: 2,
    created_at: '2021-04-24T14:33:00.681Z',
    updated_at: '2021-04-24T14:33:00.681Z',
    company: {
      id: 2,
      name: 'Netguru',
      description: 'company desc',
      logo_file_path:
        'https://upload.wikimedia.org/wikipedia/en/4/4d/Shrek_%28character%29.png',
      website_url: null,
      created_at: '2021-04-24T14:32:23.185Z',
      updated_at: '2021-04-24T14:32:23.185Z',
      locations: [
        {
          id: 6,
          name: null,
          coordinates: { x: 52.38413112832368, y: 16.921979841031867 },
          city: 'Warszawa',
          postcode: '1',
          street: 'street2',
          building_number: 2,
          room_number: null,
          created_at: '2021-04-26T18:06:11.901Z',
          updated_at: '2021-04-26T18:06:11.901Z',
        },
      ],
    },
  },
  {
    id: 6,
    title: 'Junior Android Developer',
    description: 'oferta desc',
    salary_from: 4500,
    salary_to: 6500,
    paid_till: '2021-04-24T16:32:46.000Z',
    active: true,
    profession_id: 1,
    specialization_id: 1,
    company_id: 2,
    created_at: '2021-04-24T14:33:00.681Z',
    updated_at: '2021-04-24T14:33:00.681Z',
    company: {
      id: 2,
      name: 'HL Tech',
      description: 'company desc',
      logo_file_path: 'https://swamp.neocities.org/swampy.gif',
      website_url: null,
      created_at: '2021-04-24T14:32:23.185Z',
      updated_at: '2021-04-24T14:32:23.185Z',
      locations: [
        {
          id: 6,
          name: null,
          coordinates: { x: 52.231754410206726, y: 21.005997936497742 },
          city: 'Warszawa',
          postcode: '1',
          street: 'street2',
          building_number: 2,
          room_number: null,
          created_at: '2021-04-26T18:06:11.901Z',
          updated_at: '2021-04-26T18:06:11.901Z',
        },
      ],
    },
  },
];
